### DISCUSSION TITLE
Add spinner icon

### DISCUSSION THREAD

**Discussion by brielov** [tailwindlabs/heroicons#475] [Ideas]
It would be nice to have a spinner icon to use with tailwind's `animate-spin` class name.

**Comment by dextermb** [comment]
Something along the lines of [FontAwesome's `spinner-third`](https://fontawesome.com/icons/spinner-third?style=light) would be great!

**Comment by redbastie** [comment]
+1

**Comment by timReynolds** [comment]
I know it's annoying when people just add +1 comments but this would be a really good addition. I recently wanted an icon to use with `animate-spin` and ended up copying the svg from the tailwind website as one isn't included in heroicons.

**Comment by brielov** [comment]
@timReynolds Yeah I know, I did the same thing :/

**Comment by ZhengRui** [comment]
Nice, i am not the only one to copy the svg from the tailwind website :)

**Comment by mariusmarais** [comment]
Save the Googlers some time :)

Copied from https://tailwindcss.com/docs/animation#spin example

```svg
<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>
```

**Reply by abevoelker** [reply]
Reactified:

```jsx
import React from 'react'

export default function Spinner(props) {
  const color = props.color || "text-white"
  return (
    <svg className={`animate-spin -ml-1 mr-3 h-5 w-5 ${color} ${props.extraClasses}`} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
  )
}
```
Usage:

```jsx
<Spinner color="text-black" extraClasses="self-center" />

// or just:

<Spinner />
```

**Comment by dextermb** [comment]
I've recently been using:

```html
<svg class="spinner" viewBox="0 0 50 50">
    <circle class="path" cx="25" cy="25" r="20" fill="none" stroke="currentColor" stroke-width="5" />
</svg>
```

```scss
.spinner {
  animation: rotate 2s linear infinite;
  z-index: 2;
  width: 100%;
  height: 100%;

  & .path {
    stroke-linecap: round;
    animation: dash 1.5s ease-in-out infinite;
  }
}

@keyframes rotate {
  100% {
    transform: rotate(360deg);
  }
}

@keyframes dash {
  0% {
    stroke-dasharray: 1, 150;
    stroke-dashoffset: 0;
  }
  50% {
    stroke-dasharray: 90, 150;
    stroke-dashoffset: -35;
  }
  100% {
    stroke-dasharray: 90, 150;
    stroke-dashoffset: -124;
  }
}
```
