### ISSUE TITLE
I want you to support stroke-width in heroicons/react

### ISSUE THREAD

**Issue by ru88s** [tailwindlabs/heroicons#263]
```
import { BookOpenIcon } from "@heroicons/react/outline";

<BookOpenIcon className="w-10 stroke-1"/>
```

stroke-1 does not work.
Is there a way to adjust the stroke-width?

**Comment by sanderfish** [comment]
Duplicate of https://github.com/tailwindlabs/heroicons/issues/241

**Comment by ukasyah99** [comment]
> Is there a way to adjust the stroke-width?

Yes, it's pretty simple. You just need to write some css as follows:

```css

/* Set heroicon's stroke width */
.heroicon-sw-2 path {
  stroke-width: 2 !important;
}
.heroicon-sw-1\.75 path {
  stroke-width: 1.75 !important;
}
.heroicon-sw-1\.5 path {
  stroke-width: 1.5 !important;
}
.heroicon-sw-1\.2 path {
  stroke-width: 1.2 !important;
}
```

Finally:

```js
<BookOpenIcon className="w-10 h-10 heroicon-sw-1.5" />
```

Although the above example uses the jsx version, it can also be applied to the svg version  #241 .
